; /etc/supervisor/conf.d/beninlink-worker.conf
[program:beninlink-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/beninlink/web/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopwaitsecs=3600
user=deploy
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/beninlink/web/storage/logs/worker.log
